CREATE TABLE IF NOT EXISTS downloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  platform TEXT DEFAULT 'unknown',
  channel TEXT DEFAULT 'unknown',
  title TEXT DEFAULT 'untitled',
  description TEXT,
  duration TEXT,
  thumbnail TEXT,
  filename TEXT,
  filepath TEXT,
  filesize BIGINT,
  format TEXT,
  status TEXT DEFAULT 'pending',
  progress INTEGER DEFAULT 0,
  error TEXT,
  metadata TEXT,
  rating DOUBLE PRECISION,
  source_url TEXT,
  finished_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_downloads_url ON downloads(url);
CREATE INDEX IF NOT EXISTS idx_downloads_status_created_at ON downloads(status, created_at);

CREATE TABLE IF NOT EXISTS screenshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT,
  platform TEXT,
  channel TEXT,
  title TEXT,
  filename TEXT,
  filepath TEXT,
  filesize BIGINT,
  rating DOUBLE PRECISION,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vdh_hints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT,
  platform TEXT,
  channel TEXT,
  title TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vdh_hints_created_at ON vdh_hints(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vdh_hints_platform_created_at ON vdh_hints(platform, created_at DESC);

CREATE TABLE IF NOT EXISTS download_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  download_id BIGINT NOT NULL,
  relpath TEXT NOT NULL,
  filesize BIGINT,
  mtime_ms BIGINT,
  created_at TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(download_id, relpath),
  CONSTRAINT fk_download_files_download_id
    FOREIGN KEY(download_id)
    REFERENCES downloads(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_download_files_download_id ON download_files(download_id);
CREATE INDEX IF NOT EXISTS idx_download_files_mtime ON download_files(mtime_ms DESC);
CREATE INDEX IF NOT EXISTS idx_download_files_updated ON download_files(updated_at DESC);

CREATE TABLE IF NOT EXISTS download_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  download_id BIGINT NOT NULL,
  tag TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(download_id, tag),
  CONSTRAINT fk_download_tags_download_id
    FOREIGN KEY(download_id)
    REFERENCES downloads(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_download_tags_tag_download_id ON download_tags(tag, download_id);
CREATE INDEX IF NOT EXISTS idx_download_tags_download_id ON download_tags(download_id);

CREATE TABLE IF NOT EXISTS tags (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS media_tags (
  kind TEXT NOT NULL,
  media_id TEXT NOT NULL,
  tag_id INTEGER NOT NULL,
  PRIMARY KEY (kind, media_id, tag_id),
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
